services:
  wordpress:
    image: wordpress:latest
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CACHE_HOST: redis_cache
      WORDPRESS_CACHE_PORT: 6379
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - backend
      - frontend
    deploy:
      replicas: 2 

  wordpress_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

  redis_cache:
    image: redis:latest
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend
    depends_on:
      - wordpress

networks:
  backend:
  frontend:

volumes:
  wordpress_data:
  db_data:
